const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Pin,
		C3.Behaviors.bound,
		C3.Behaviors.MoveTo,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Behaviors.Timer,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Spritefont2,
		C3.Plugins.NinePatch,
		C3.Plugins.Particles,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.windowheight,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Behaviors.MoveTo.Acts.MoveToPosition
	];
};
self.C3_JsPropNameTable = [
	{caixa: 0},
	{JogoForca: 0},
	{letra: 0},
	{Piscar: 0},
	{Letras: 0},
	{WIFI: 0},
	{TESTEB: 0},
	{PERGUNTAS: 0},
	{Textoforca: 0},
	{TextoQualAPalavra: 0},
	{CORACAOTENTATIVA: 0},
	{TextoVida: 0},
	{Confirmar: 0},
	{delete: 0},
	{espaço: 0},
	{Sprite3: 0},
	{Fundo: 0},
	{MinidevQuebracabeca: 0},
	{Esquerda: 0},
	{Direita: 0},
	{COLOCADA: 0},
	{USADA: 0},
	{Variável1: 0},
	{ArrastarSoltar: 0},
	{Fixar: 0},
	{RestritoAoLayout: 0},
	{MoverPara: 0},
	{Pecas: 0},
	{REFERENCIA: 0},
	{TELA: 0},
	{PontoPECA: 0},
	{Pecas2: 0},
	{PlanoDeFundo: 0},
	{CartaoFrenteQuadro: 0},
	{CartaCima: 0},
	{CartaAtrás: 0},
	{Mouse: 0},
	{Matriz: 0},
	{Acertos: 0},
	{chances: 0},
	{txtpontos: 0},
	{txtpontosChances: 0},
	{PlanoDeFundoEmBlocos: 0},
	{logo: 0},
	{GJogar: 0},
	{jogar: 0},
	{minidevPc: 0},
	{Cronômetro: 0},
	{txt_cronometro: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{minidevTriste: 0},
	{Sprite5: 0},
	{minidevjogando: 0},
	{Estrelaacertos: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{minidevfeliz: 0},
	{estrelas: 0},
	{creditos: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{Áudio: 0},
	{retornar: 0},
	{Toque: 0},
	{Sprite: 0},
	{Teclado: 0},
	{Sprite7: 0},
	{FonteDeSprites: 0},
	{BOTAOQUEBRACABECA: 0},
	{TelaMododeJogo: 0},
	{ID: 0},
	{MATCH: 0},
	{"9secções2": 0},
	{Telaexibicao: 0},
	{telaexibicaoreferencia: 0},
	{BOTAOJOGODAMEMORIA: 0},
	{BOTAOJOGODAFORCA: 0},
	{Esmaecer: 0},
	{Partículas: 0},
	{Letra: 0},
	{CartaoMatriz: 0},
	{Espaço1: 0},
	{Cartão1: 0},
	{Espaço2: 0},
	{Cartão2: 0},
	{AtualColuna: 0},
	{AtualLinha: 0},
	{CartaoAtual: 0},
	{GChances: 0},
	{GPartidas: 0},
	{GCartaoResetar: 0},
	{GNumeroCartasEmbaralhar: 0},
	{GMargemTopo: 0},
	{GMargemEsquerda: 0},
	{GEspaçoEntreCartao: 0},
	{GCartaoLargura: 0},
	{GCartaoAltura: 0},
	{GNumerosColunas: 0},
	{GNumerosLinha: 0},
	{GNumeroCartas: 0},
	{GContarCartasEscolhidas: 0},
	{GPrimeiroQuadro: 0},
	{GSegundoQuadro: 0},
	{GReiniciarJogo: 0},
	{GCartasReveladas: 0},
	{GCronometro: 0},
	{GVitoria: 0},
	{Palavras: 0},
	{ACERTOS: 0},
	{TIKTOK: 0},
	{GRUPO: 0},
	{VIDA: 0},
	{INTERNET: 0},
	{HTML: 0},
	{COMPUTADOR: 0},
	{JAVASCRIPT: 0},
	{ANDROID: 0},
	{GOOGLE: 0},
	{WINDOWS: 0},
	{INSTAGRAM: 0},
	{IMPRESSORA: 0},
	{NOTEBOOK: 0},
	{PECA: 0},
	{CORRETO: 0},
	{Peca_disponivel: 0},
	{Peca_atual_quadro: 0}
];

self.InstanceType = {
	JogoForca: class extends self.IArrayInstance {},
	Letras: class extends self.ISpriteInstance {},
	PERGUNTAS: class extends self.ISpriteInstance {},
	Textoforca: class extends self.ITextInstance {},
	TextoQualAPalavra: class extends self.ITextInstance {},
	CORACAOTENTATIVA: class extends self.ISpriteInstance {},
	TextoVida: class extends self.ITextInstance {},
	caixa: class extends self.ISpriteInstance {},
	Confirmar: class extends self.ISpriteInstance {},
	delete: class extends self.ISpriteInstance {},
	espaço: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Fundo: class extends self.ISpriteInstance {},
	MinidevQuebracabeca: class extends self.ISpriteInstance {},
	Esquerda: class extends self.ISpriteInstance {},
	Direita: class extends self.ISpriteInstance {},
	Pecas: class extends self.ISpriteInstance {},
	REFERENCIA: class extends self.ISpriteInstance {},
	TELA: class extends self.ISpriteInstance {},
	PontoPECA: class extends self.ISpriteInstance {},
	Pecas2: class extends self.ISpriteInstance {},
	PlanoDeFundo: class extends self.ITiledBackgroundInstance {},
	CartaAtrás: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Matriz: class extends self.IArrayInstance {},
	Acertos: class extends self.ISpriteInstance {},
	chances: class extends self.ISpriteInstance {},
	txtpontos: class extends self.ITextInstance {},
	txtpontosChances: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	logo: class extends self.ISpriteInstance {},
	jogar: class extends self.ISpriteInstance {},
	minidevPc: class extends self.ISpriteInstance {},
	txt_cronometro: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	minidevTriste: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	minidevjogando: class extends self.ISpriteInstance {},
	Estrelaacertos: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	minidevfeliz: class extends self.ISpriteInstance {},
	estrelas: class extends self.ISpriteInstance {},
	creditos: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	Áudio: class extends self.IInstance {},
	retornar: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	BOTAOQUEBRACABECA: class extends self.ISpriteInstance {},
	TelaMododeJogo: class extends self.ISpriteInstance {},
	_9secções2: class extends self.IWorldInstance {},
	Telaexibicao: class extends self.ISpriteInstance {},
	telaexibicaoreferencia: class extends self.ISpriteInstance {},
	BOTAOJOGODAMEMORIA: class extends self.ISpriteInstance {},
	BOTAOJOGODAFORCA: class extends self.ISpriteInstance {},
	Partículas: class extends self.IParticlesInstance {},
	Letra: class extends self.ISpriteInstance {}
}